name: Native Gems
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize]
    branches:
      - '*'

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        platform: ["ruby", "x86_64-darwin", "arm64-darwin", "x86_64-linux", "arm64-linux"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm Gemfile.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler: latest
          bundler-cache: true
      - run: "bundle exec rake gem:${{matrix.platform}}"
      - uses: actions/upload-artifact@v4
        with:
          name: gem-${{matrix.platform}}
          path: pkg
          retention-days: 1

  vanilla-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-ruby
          path: pkg
      - run: "gem install pkg/litestream-*.gem"
      - run: "litestream version"

  linux-x86_64-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x86_64-linux
          path: pkg
      - run: "gem install pkg/litestream-*.gem"
      - run: "litestream version"

  linux-arm64-install:
    needs: ["package"]
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-arm64-linux
          path: pkg
      - run: "gem install pkg/litestream-*.gem"
      - run: "litestream version"

  darwin-x86_64-install:
    needs: ["package"]
    runs-on: macos-13
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v4
        with:
          name: gem-x86_64-darwin
          path: pkg
      - run: "gem install pkg/litestream-*.gem"
      - run: "litestream version"

  darwin-arm64-install:
    needs: ["package"]
    runs-on: macos-14
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: actions/download-artifact@v3
        with:
          name: gem-arm64-darwin
          path: pkg
      - run: "gem install pkg/litestream-*.gem"
      - run: "litestream version"